<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        MDIconButton:
            icon: 'cogs'
            icon_size: '40dp'
            pos_hint: {"right": 1, "top": 1}

        MDLabel:
            text: "Shooter Game"
            font_size: '35dp'
            size_hint_y: 0.2
            halign: 'center'

        Image:
            source: 'spaceship.png'

        MDRaisedButton:
            text: 'GAME'
