<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        MDIconButton:
            icon: 'cog'
            pos_hint: {'right': 1, 'top': 1}
            icon_size: '40dp'
            
        MDLabel:
            text: "Shooter Game"
            font_size: '30dp'
            halign: 'center'
            size_hint_y: 0.2

        Image:
            source: 'spaceship.png'
            size_hint_y: 0.7
            allow_stretch: True

        MDRaisedButton:
            text: 'Game'
            pos_hint: {'center_x': 0.5}

<Ship@Image>:
    source: 'spaceship.png'
    size_hint: None, None
    
<GameScreen>:
    MDFloatLayout:
        MDFloatLayout:
            id: game

            MDFloatLayout:
                id: back

            MDFloatLayout:
                id: front
                
                Ship:
                    id: ship
                    center: root.center

        MDFloatLayout:
            id: interface

            MDBoxLayout:
                padding: '20dp'
                spacing: '20dp'

                MDFloatingActionButton:
                    icon: 'arrow-left-bold'
                    on_press: root.presskey('left')
                    on_release: root.releasekey('left')

                MDFloatingActionButton:
                    icon: 'arrow-right-bold'
                    on_press: root.presskey('right')
                    on_release: root.releasekey('right')

                MDFloatingActionButton:
                    icon: 'arrow-up-bold'
                    on_press: root.presskey('shot')
                    on_release: root.releasekey('shot')

<Shot>:
    size_hint: None, None
    size: 20, 20
    md_bg_color: app.theme_cls.primary_color
