<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        MDIconButton:
            icon: 'cog'
            pos_hint: {'right': 1, 'top': 1}
            icon_size: '40dp'
            
        MDLabel:
            text: "Shooter Game"
            font_size: '30dp'
            halign: 'center'
            size_hint_y: 0.2

        Image:
            source: 'spaceship.png'
            size_hint_y: 0.7
            allow_stretch: True

        MDRaisedButton:
            text: 'Game'
            pos_hint: {'center_x': 0.5}
            on_press:
                root.manager.current = 'game'

<Ship@Image>:
    size_hint: None, None
    
<PlayerShip@Ship>:
    source: 'spaceship.png'

<EnemyShip@Ship>:
    source: 'ufo.png'  

<GameScreen>:
    MDFloatLayout:
        MDFloatLayout:
            id: game

            MDFloatLayout:
                id: back

            MDFloatLayout:
                id: front
                
                PlayerShip:
                    id: ship
                    pos: root.center_x, dp(50)

        MDFloatLayout:
            id: interface

            MDBoxLayout:
                padding: '20dp'
                spacing: '20dp'

                Widget:

                MDFloatingActionButton:
                    icon: 'pause'
                    pos_hint: {'top': 1}
                    on_press: root.show_menu()

                Widget:

            MDBoxLayout:
                padding: '20dp'
                spacing: '20dp'

                MDFloatingActionButton:
                    icon: 'arrow-left-bold'
                    on_press: root.pressKey('left')
                    on_release: root.releaseKey('left')

                MDFloatingActionButton:
                    icon: 'arrow-right-bold'
                    on_press: root.pressKey('right')
                    on_release: root.releaseKey('right')

                Widget:

                MDFloatingActionButton:
                    icon: 'arrow-up-bold'
                    on_press: root.pressKey('shot')
                    on_release: root.releaseKey('shot')

<Shot>:
    size_hint: None, None
    size: 20, 20
    md_bg_color: app.theme_cls.primary_color

<GameOverScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        MDLabel:
            text: "GAME OVER"
            font_size: '50dp'
            halign: 'center'
            color: app.theme_cls.accent_color

        MDIcon:
            icon: 'skull'
            font_size: '100dp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5}
            color: app.theme_cls.accent_color

        Widget:
            size_hint_y: 0.5

        MDRaisedButton:
            text: 'Menu'
            pos_hint: {'center_x': 0.5}
            on_press:
                root.manager.current = 'main'
